Repository falcosecurity/plugin-sdk-cpp, pull requests merged in 2023-11, with the labels that each got.

#27 update: add async event handler factory
  examples/syscall_async/plugin.cpp
  include/falcosecurity/async_event_handler.h
  include/falcosecurity/internal/plugin_mixin_async.h
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/L

#28 update: apply clang format
  examples/syscall_async/plugin.cpp
  include/falcosecurity/async_event_handler.h
  include/falcosecurity/internal/plugin_mixin_async.h
Labels: needs-kind, dco-signoff: yes, size/M, lgtm, approved

#30 update(Makefile): add install and uninstall targets
  Makefile
Labels: needs-kind, dco-signoff: yes, lgtm, approved, area/build, size/S

#24 Prevent inttypes.h from being wrapped in namespace
  include/falcosecurity/internal/deps.h
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XS, area/plugin-sdk
